### ISSUE TITLE
Syntax Error on Line 784 in Latest Update in Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by novascout** [kendryte/kflash.py#10]
While attempting to flash K210 received syntax error on line 784 in latest update to code. OS: Ubuntu 16.04 LTS.

> 
> ~/kendryte$ python3 kflash.py ./kendryte-standalone-sdk/build/lcd.bin
>   File "kflash.py", line 784
>     fFlashList = open(f'{tmpdir}/flash-list.json', "r")
>                                                 ^
> SyntaxError: invalid syntax

**Comment by minux** [comment]
f'' format string is introduced in Python 3.6. I think we need to define a
minimum Python 3 version for kflash
(and consider adding using travis CI to check.)

@novascout what's your Python 3 version (python3 --version)? In the
meantime, you could use python 3.6
or higher to run kflash.py.

**Comment by minux** [comment]
@MarsTechHAN please change `f''` format strings to use `os.path.join`
instead.
(Please also add "Fixes #10" to the commit message.)

Not only is `os.path.join` more portable (no hardcode of dir separator),
this change will remove the Python 3.6 dependency, which is unnecessary.
Actually, if possible, please also clean up the naming conventions in
surrounding code to match the rest of the file.

Thanks.

**Comment by northerntrend** [comment]
> f'' format string is introduced in Python 3.6. I think we need to define a minimum Python 3 version for kflash (and consider adding using travis CI to check.) @novascout what's your Python 3 version (python3 --version)? In the meantime, you could use python 3.6 or higher to run kflash.py.

Hi @minux - I'm using  Python 3.5.2. I'll make the change to the script and retest. I suspect there will be many that aren't using Python 3.6 so this will definitely make it more portable. Thanks.

**Comment by novascout** [comment]
Hi @minux - I'm running Python 3.5.2. I'll make the changes and report back if there are any issues. I suspect several others are not running Python 3.6 so this change will definitely make it more portable.

-Thanks

**Comment by novascout** [comment]
As per @minux instructions kflash.py is now working with Python 3.5.2. After importing os, the following modifications were made:

```
fFlashList = open(os.path.join(tmpdir,'flash-list.json'), "r")
...
firmware_bin = open(os.path.join(tmpdir,lBinFiles["bin"]), "rb")      
```
