### ISSUE TITLE
seems something is error

### ISSUE THREAD

**Issue by xelll** [kendryte/kflash.py#11]
https://github.com/kendryte/kflash.py/blob/30ab2a01ea2bba0f9ec254b934846225e6f64749/kflash.py#L665
iv should be IV

**Comment by ly0** [comment]
Do you mean it should be uppercase here?

**Comment by minux** [comment]
why it should be "IV"?

https://github.com/kendryte/kflash.py/blob/30ab2a01ea2bba0f9ec254b934846225e6f64749/kflash.py#L215

**Comment by xelll** [comment]
emmm, my isp.py is old version, it is different at here .....
