### ISSUE TITLE
Response timeout

### ISSUE THREAD

**Issue by Masi2018** [kendryte/kflash.py#19]
Hi All,
When I try to run this I am getting .[ERROR] Response timeout error. I am using K233 dev board, I haven't had issue with the previous version.

**Comment by yujiageng** [comment]
same problem

**Comment by ATmega8** [comment]
`[INFO] COM Port Auto Detected, Selected  /dev/ttyUSB1 
[INFO] Default baudrate is 115200 , later it may be changed to the value you set. 
[INFO] Trying to Enter the ISP Mode... 
.[ERROR] Response timeout `

like this? 

I tried to change

`
436                sys.exit(1)
437                #raise TimeoutError
`
to
`
436                #sys.exit(1)
437                raise TimeoutError
`
It worked

`[INFO] COM Port Auto Detected, Selected  /dev/ttyUSB0 
[INFO] Default baudrate is 115200 , later it may be changed to the value you set. 
[INFO] Trying to Enter the ISP Mode... 
.[ERROR] Response timeout 
_[ERROR] Response timeout 
.[ERROR] Response timeout 
_[ERROR] Response timeout 
.[ERROR] Response timeout 
_[ERROR] Response timeout 
.[ERROR] Response timeout 
_[ERROR] Response timeout 
.[ERROR] Response timeout 
_[ERROR] Response timeout 
.[ERROR] Response timeout 
_[ERROR] Response timeout 
.[ERROR] Response timeout 
_[ERROR] Response timeout 
.[ERROR] Response timeout 
_[ERROR] Response timeout 
.[ERROR] Response timeout 
_[ERROR] Response timeout 
.[ERROR] Response timeout 
_[ERROR] Response timeout 
.[ERROR] Response timeout 
_[ERROR] Response timeout 
.[ERROR] Response timeout 
_[ERROR] Response timeout 
.[ERROR] Response timeout 
_c0
[INFO] Greeting Message Detected, Start Downloading ISP 
Downloading ISP: |█-------------------------------------------------| 2.9% ComplDownloading ISP: |██------------------------------------------------| 5.9% ComplDownloading ISP: |████----------------------------------------------| 8.8% ComplDownloading ISP: |█████---------------------------------------------| 11.8% CompDownloading ISP: |███████-------------------------------------------| 14.7% CompDownloading ISP: |████████------------------------------------------| 17.6% CompDownloading ISP: |██████████----------------------------------------| 20.6% CompDownloading ISP: |███████████---------------------------------------| 23.5% CompDownloading ISP: |█████████████-------------------------------------| 26.5% CompDownloading ISP: |██████████████------------------------------------| 29.4% CompDownloading ISP: |████████████████----------------------------------| 32.4% CompDownloading ISP: |█████████████████---------------------------------| 35.3% CompDownloading ISP: |███████████████████-------------------------------| 38.2% CompDownloading ISP: |████████████████████------------------------------| 41.2% CompDownloading ISP: |██████████████████████----------------------------| 44.1% CompDownloading ISP: |███████████████████████---------------------------| 47.1% CompDownloading ISP: |█████████████████████████-------------------------| 50.0% CompDownloading ISP: |██████████████████████████------------------------| 52.9% CompDownloading ISP: |███████████████████████████-----------------------| 55.9% CompDownloading ISP: |█████████████████████████████---------------------| 58.8% CompDownloading ISP: |██████████████████████████████--------------------| 61.8% CompDownloading ISP: |████████████████████████████████------------------| 64.7% CompDownloading ISP: |█████████████████████████████████-----------------| 67.6% CompDownloading ISP: |███████████████████████████████████---------------| 70.6% CompDownloading ISP: |████████████████████████████████████--------------| 73.5% CompDownloading ISP: |██████████████████████████████████████------------| 76.5% CompDownloading ISP: |███████████████████████████████████████-----------| 79.4% CompDownloading ISP: |█████████████████████████████████████████---------| 82.4% CompDownloading ISP: |██████████████████████████████████████████--------| 85.3% CompDownloading ISP: |████████████████████████████████████████████------| 88.2% CompDownloading ISP: |█████████████████████████████████████████████-----| 91.2% CompDownloading ISP: |███████████████████████████████████████████████---| 94.1% CompDownloading ISP: |████████████████████████████████████████████████--| 97.1% CompDownloading ISP: |██████████████████████████████████████████████████| 100.0% Complete
[INFO] Booting From 0x80000000 
[INFO] Wait For 0.3 second for ISP to Boot 
5b44454255475d20696e20466c617368204d6f64650d0a5b44454255475d20466c6173684d6f64653a20696e6974207561727420696e7465727570740d0a5b44454255475d20466c6173684d6f64653a206c6f6f700d0ac0[INFO] Boot to Flashmode Successfully 
[INFO] Selected Flash:  On-Board 
Downloading: |██████████████████████████████████████████████████| 100.0% Complete
[INFO] Rebooting... 

`

**Comment by vowstar** [comment]
Please retry latest version

**Comment by CyanBlob** [comment]
I'm having the same issue on my K210 board. My repo is up to date. Do you have any other suggestions?

**Comment by vowstar** [comment]
I think this problem was fixed in commit https://github.com/kendryte/kflash.py/commit/b7a3451b1cde28e2b7dacbcef8d51dfa44802062

The reason why "Response timeout" is UART transmit error when initializing SPI3, and then retry initialize SPI3, the ISP program hang.
So this commit fixed this problem to ensure the SPI3 only initialization once.
Please try with latest commit.

**Comment by CyanBlob** [comment]
It is working on a different PC now, but this is the first time I've tried it on this system.  
I can try to test again tomorrow with the PC that was giving me issues, but I think that https://github.com/kendryte/kflash.py/commit/b7a3451b1cde28e2b7dacbcef8d51dfa44802062 fixed it
Thanks a lot!
