### ISSUE TITLE
pip3 install crypto may not work

### ISSUE THREAD

**Issue by Aostas** [kendryte/kflash.py#3]
I tested the kflash.py on two devices.pip3 install crypto works on the ubuntu18.04 with python2.7.15rc1.And it doesn't work on the ubuntu 16.04 with python 3.5.2.
In the case of ubuntu 16.04 with python 3.5.2,It doesn't matter if I install crypto or not.I shoud install pycrypto to fix it.

**Comment by minux** [comment]
@ly0 I'm wondering if we should just include a pure-Python implementation
of AES128-CBC into `kentool.py` to get rid of the PyCrypto dependency: the
serial download is very slow so I don't think the encryption performance
matters.
Alternatively, we can do the import only when the user requests firmware
encryption.

**Comment by ly0** [comment]
@minux Yep, I agree with you, I will replace a pure python implement of AES-128-CBC to remove pycryptodome dependency.

**Comment by ly0** [comment]
@Aostas Latest kflash.py has removed pycryptodome dependency. :-)
