### ISSUE TITLE
"something's wrong" with the CH340 on KD233

### ISSUE THREAD

**Issue by MarsTechHAN** [kendryte/kflash.py#6]
#### When using the kflash.py, the otp boot fails to start the app, may due to file inconsistent during the download stage.
> interesting, something's wrong, boot failed with exit code 233, go to find your vendor.
--------- 
![image](https://user-images.githubusercontent.com/10462805/48465953-6a650380-e7b2-11e8-8b73-c00ae5019c3d.png)
---------
#### It seems like only the KD233 have this issue. Dan is working ok. (but for the old version, both is working)

auto_isp.py is grabbed from https://github.com/kendryte/kflash.py/commit/0dd769cf740b47b80d86ca2a65672387509da9c8 and kflash.py is grabbed from https://github.com/kendryte/kflash.py/commit/adc3d69056d617ec2e4967d767c62b1e597eee55

I noticed that the only difference that may be related to this issue is @vowstar add the "change the baudrate function" while replease the whole blob. https://github.com/kendryte/kflash.py/commit/0450ee7901b2b4dc3d3330b0af7f36c1e7e2dd20

**Comment by ly0** [comment]
I will update a niubility isp_flash blob.

**Comment by MarsTechHAN** [comment]
### It seems like the problem is not at that blob. 
If I comment out 
```python
loader.change_baudrate(args.baudrate)
```
Everything just works fine for both platforms. 

#### Further investigation finds that the CH340 on KD233 may be a fake chip.
<img src="https://user-images.githubusercontent.com/10462805/48565129-cbc9c700-e8c5-11e8-904a-90beded301af.png" alt="drawing" width="200"/>                        <img src="https://user-images.githubusercontent.com/10462805/48565134-ccfaf400-e8c5-11e8-9675-0ccad440b3ed.png" alt="drawing" width="200"/>

#### The etching of the CH340 on KD233 appears to be lighter than that on Dan.
------- 
#### For kendryte-flash-windows project, it closes the serial, then enable it again. Which I tried on pyserial, it yields some extra issues on DTR/RTS, which I am currently trying to figure it out.
```c#
 public async Task ChangeBaudRate()
        {
            var status = JobItemsStatus[JobItemType.ChangeBaudRate];
            CurrentJob = JobItemType.ChangeBaudRate;
            await DoJob(status, () =>
            {
                return Task.Run(async () =>
                {
                    var buffer = new byte[4 * 5];
                    var payload = new ArraySegment<byte>(BitConverter.GetBytes(_baudRate));
                    SendPacket(buffer, (ushort)FlashModeResponse.Operation.ISP_UARTHS_BAUDRATE_SET, 0, payload: payload);

                    _port.Close();
                    await Task.Delay(50);
                    _port.BaudRate = _baudRate;
                    _port.Open();
                });
            });
        }
```
#### Anyway... still want to opensource the ISP Source code :3

**Comment by vowstar** [comment]
> I will update a niubility isp_flash blob.

This issue will not close until @ly0 update a **niubility** isp_flash blob.

**Comment by vowstar** [comment]
isp_flash blob updated, I think this issue fixed

**Comment by fortunerains** [comment]
after I  download bin file using k flash unitity ,I open the COM and see the printing, Has the problem been solved
