### ISSUE TITLE
Need some other ways to pack the blobs

### ISSUE THREAD

**Issue by MarsTechHAN** [kendryte/kflash.py#7]
In order to make the script work, kflash required two huge blobs, -> 
transformation table for AES and isp program.

#### Those two huge blob lying between the script makes the code a little bit of dirty. And we need some methods to solve it.
-------- 
Some ideas:
0. At least moves them to the bottom of the program
1. We can just squeeze them in the very bottom of the program inside a line of comments, and use IO to read the script itself to extra the data.
2. Some ways to binarize it, and apply the same methods, not sure whether it will work.

**Comment by ly0** [comment]
But it works, that's all we want. 😄
